[workspace]
members = ["bevy_rapier2d", "bevy_rapier3d"]
resolver = "2"

[profile.release]
codegen-units = 1

[patch.crates-io]
bevy = { git = "https://github.com/bevyengine/bevy", rev = "019432af2e9c26dfbd6d79dda0ad107811874124" }
nalgebra = { git = "https://github.com/Dig-Doug/nalgebra", branch = "glam-024" }
#nalgebra = { path = "../nalgebra" }
#parry2d = { path = "../parry/crates/parry2d" }
#parry3d = { path = "../parry/crates/parry3d" }
#rapier2d = { path = "../rapier/crates/rapier2d" }
#rapier3d = { path = "../rapier/crates/rapier3d" }

#nalgebra = { git = "https://github.com/dimforge/nalgebra", branch = "dev" }
#parry2d = { git = "https://github.com/dimforge/parry", branch = "master" }
#parry3d = { git = "https://github.com/dimforge/parry", branch = "master" }
#rapier2d = { git = "https://github.com/dimforge/rapier", branch = "character-controller" }
#rapier3d = { git = "https://github.com/dimforge/rapier", branch = "character-controller" }
